version: '3'
volumes:
  grafana-storage:
  prometheus:
  alertmanager-data:
services:
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/prometheus-data/prometheus.yml"]
    volumes:
      - ./prometheus-data:/prometheus-data
      - prometheus:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    depends_on:
      - prometheus
  blackbox:
    image: prom/blackbox-exporter
    ports:
    - "9115:9115"
    command:
    - --config.file=/etc/blackbox/blackbox.yml
    volumes:
    - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    depends_on:
    - prometheus

